apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: ${secretProviderClassName}
spec:
  provider: azure
  secretObjects:
  - data:
    - key: username
      objectName: ${secret1Alias}
    - key: password
      objectName: ${secret2Alias}
    secretName: ${secretName}
    type: Opaque
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: ${keyVaultName}
    cloudName: AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: ${secret1Name}
          objectAlias: ${secret1Alias}
          objectType: secret
          objectVersion: ""
        - |
          objectName: ${secret2Name}
          objectAlias: ${secret2Alias}
          objectType: secret
          objectVersion: ""
    resourceGroup: ${resourceGroupName}
    subscriptionId: ${subscriptionId}
    tenantId: ${tenantId}